/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.checkinn.setting;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.CardLayout;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import lk.checkinn.util.AppIconUtil;

/**
 *
 * @author DELL
 */
public class settingPannel extends javax.swing.JFrame {
    
    private RoomTypesPanel roomTypesPanel;
    private RoomNamesPanel roomNamesPanel;
    private RoomRatesPanel roomRatesPanel;
    
    private CardLayout contentPanelLayout;
    
    public settingPannel() {
        initComponents();
        init();
        loadPanels();
    }
    
    private void init(){
        AppIconUtil.applyIcon(this);
        
        roomTypesBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        roomNamesBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        roomRatesBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        
        menuItemPanel.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        contentPanel.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        
//        roomTypesBtn.setIcon(new FlatSVGIcon("lk/jiat/smarttrading/img/dashboard.svg",20,20));
    }
    
    private void loadPanels(){
        if(contentPanelLayout == null && contentPanel.getLayout() instanceof CardLayout){
            this.contentPanelLayout = (CardLayout)contentPanel.getLayout();
        }
        
        this.roomTypesPanel = new RoomTypesPanel();
        this.roomNamesPanel = new RoomNamesPanel();
        this.roomRatesPanel = new RoomRatesPanel();
        
        this.roomTypesPanel.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        this.roomNamesPanel.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        this.roomRatesPanel.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        
        this.contentPanel.add(roomTypesPanel, "room_types_panel");
        this.contentPanel.add(roomNamesPanel, "room_names_panel");
        this.contentPanel.add(roomRatesPanel, "room_rates_panel");
        SwingUtilities.updateComponentTreeUI(contentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menuItemPanel = new javax.swing.JPanel();
        roomTypesBtn = new javax.swing.JButton();
        roomNamesBtn = new javax.swing.JButton();
        roomRatesBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("System Configuration");
        setBackground(new java.awt.Color(84, 84, 84));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        jLabel1.setText("Sysyem Configuration");

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jLabel2.setText("Configure this system with rooms and costs associated with the hotel, motel or guest house");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        menuItemPanel.setBackground(new java.awt.Color(84, 84, 84));

        roomTypesBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        roomTypesBtn.setText("Room Types");
        roomTypesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypesBtnActionPerformed(evt);
            }
        });

        roomNamesBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        roomNamesBtn.setText("Room Names");
        roomNamesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNamesBtnActionPerformed(evt);
            }
        });

        roomRatesBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        roomRatesBtn.setText("Room Rates");
        roomRatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomRatesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuItemPanelLayout = new javax.swing.GroupLayout(menuItemPanel);
        menuItemPanel.setLayout(menuItemPanelLayout);
        menuItemPanelLayout.setHorizontalGroup(
            menuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomTypesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(roomNamesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(roomRatesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        menuItemPanelLayout.setVerticalGroup(
            menuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItemPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roomTypesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(roomNamesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(roomRatesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(84, 84, 84));
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roomTypesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypesBtnActionPerformed
        // TODO add your handling code here:
        this.contentPanelLayout.show(contentPanel,"room_types_panel");
    }//GEN-LAST:event_roomTypesBtnActionPerformed

    private void roomNamesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNamesBtnActionPerformed
        // TODO add your handling code here:
        this.contentPanelLayout.show(contentPanel, "room_names_panel");
    }//GEN-LAST:event_roomNamesBtnActionPerformed

    private void roomRatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomRatesBtnActionPerformed
        // TODO add your handling code here:
        this.contentPanelLayout.show(contentPanel, "room_rates_panel");
    }//GEN-LAST:event_roomRatesBtnActionPerformed
public static void main(String args[]) {

        FlatIntelliJLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingPannel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menuItemPanel;
    private javax.swing.JButton roomNamesBtn;
    private javax.swing.JButton roomRatesBtn;
    private javax.swing.JButton roomTypesBtn;
    // End of variables declaration//GEN-END:variables
}
