/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk.checkinn.setting;

import com.formdev.flatlaf.FlatClientProperties;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class RoomRatesPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomRatesPanel
     */
    public RoomRatesPanel() {
        initComponents();

        loadRoomType();

        loadRoomRates();
        jPanel1.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        jPanel2.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        jPanel3.putClientProperty(FlatClientProperties.STYLE, "arc:20");
    }

    private void loadRoomType() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/checkinn_db", "root", "@Jonathan123");
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("SELECT * FROM `room_type`");

            Vector<String> v = new Vector();
            v.add("Select Room Type");

            while (r.next()) {
                String type = r.getString("type");
//                System.out.println(type);
                v.add(type);
            }

            DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel(v);
            roomTypeComboBoxModel.setModel(dcm);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        deleteBtn_roomrates = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        roomTypeComboBoxModel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        adultRateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        childRateField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(84, 84, 84));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add / Remove Room Rates");

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add or Remove the room rates used in the hotel, motel or guest house");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Room Rates");

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Room Type");

        deleteBtn_roomrates.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        deleteBtn_roomrates.setText("Delete");
        deleteBtn_roomrates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn_roomratesActionPerformed(evt);
            }
        });

        insertBtn.setBackground(new java.awt.Color(51, 102, 255));
        insertBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(255, 255, 255));
        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        roomTypeComboBoxModel.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        roomTypeComboBoxModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomTypeComboBoxModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeComboBoxModelActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adult Rate");

        adultRateField.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Child Rate");

        childRateField.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(roomTypeComboBoxModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(deleteBtn_roomrates)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(adultRateField)
                    .addComponent(childRateField))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomTypeComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adultRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn_roomrates, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room Rates");

        jTable1.setBackground(new java.awt.Color(84, 84, 84));
        jTable1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Room Type", "Adult Rate", "Child Rate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        String selectedRoomType = (String) roomTypeComboBoxModel.getSelectedItem();
        String adultRate = adultRateField.getText();
        String childRate = childRateField.getText();

//        System.out.println(selectedRoomType);
//        System.out.println(adultRate);
//        System.out.println(childRate);
        if (selectedRoomType.equals("Select Room Type")) {
            JOptionPane.showMessageDialog(this, "Please select a room type before inserting.",
                    "Room Type Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (adultRate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the adult rate before inserting.",
                    "Rate Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (childRate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter child rates before inserting.",
                    "Rate Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!adultRate.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric value for Adult Rate.",
                    "Adult Rate Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!childRate.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric value for Child Rate.",
                    "Child Rate Validation",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Double adultRateDouble = Double.parseDouble(adultRate);
            Double childRateDouble = Double.parseDouble(childRate);

//            System.out.println(selectedRoomType);
//            System.out.println(adultRateDouble);
//            System.out.println(childRateDouble);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/checkinn_db", "root", "@Jonathan123");
            Statement s1 = con1.createStatement();
            ResultSet rs1 = s1.executeQuery("SELECT `id` FROM `room_type` WHERE `type` = '" + selectedRoomType + "'");

            if (rs1.next()) {
                int roomTypeId = rs1.getInt("id");

                ResultSet rsCheck = s1.executeQuery("SELECT * FROM `rates` WHERE `room_type_id` = '" + roomTypeId + "'");
                if (rsCheck.next()) {
                    JOptionPane.showMessageDialog(this, "Rates already exist for this room type.\nPlease update instead of adding a new entry.",
                            "Duplicate Entry", JOptionPane.WARNING_MESSAGE);

                    roomTypeComboBoxModel.setSelectedIndex(0);
                    adultRateField.setText("");
                    childRateField.setText("");
                    return;
                }

                s1.executeUpdate("INSERT INTO `rates` (`adult_rate`,`child_rate`,`room_type_id`)"
                        + "VALUES ('" + adultRateDouble + "', '" + childRateDouble + "', '" + roomTypeId + "') ");
                
                roomTypeComboBoxModel.setSelectedIndex(0);
                adultRateField.setText("");
                childRateField.setText("");
                
                loadRoomRates();

                JOptionPane.showMessageDialog(this, "Rates inserted successfully.",
                        "Insert Success",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e1) {
            e1.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values for rates.",
                    "Number Format Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_insertBtnActionPerformed

    private void loadRoomRates() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con3 = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/checkinn_db", "root", "@Jonathan123");
            Statement s3 = con3.createStatement();
            ResultSet rs3 = s3.executeQuery("SELECT * FROM `rates` INNER JOIN `room_type` ON `rates`.`room_type_id` = `room_type`.`id`");

            Vector<Vector> ratesBacket = new Vector();

            while (rs3.next()) {
                Vector<String> ratesTableRow = new Vector();
                ratesTableRow.add(rs3.getString("adult_rate"));
                ratesTableRow.add(rs3.getString("child_rate"));
                ratesTableRow.add(rs3.getString("room_type.type"));

                ratesBacket.add(ratesTableRow);
            }

            Vector<String> ratesTableColumns = new Vector();
            ratesTableColumns.add("Adult Rate");
            ratesTableColumns.add("Child Rate");
            ratesTableColumns.add("Room Type");

            DefaultTableModel dtm = new DefaultTableModel(ratesBacket, ratesTableColumns);
            jTable1.setModel(dtm);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void roomTypeComboBoxModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeComboBoxModelActionPerformed
//        // TODO add your handling code here:
//        String selectedRoomType = (String) roomTypeComboBoxModel.getSelectedItem();
//        
//        if(selectedRoomType.equals("Family")){
//            childRateField.setEditable(true);
//            childRateField.setText("");
//        } else if(selectedRoomType.equals("Couple") || selectedRoomType.equals("Single")){
//            childRateField.setEditable(false);
//            childRateField.setText("0.0");
//        };
    }//GEN-LAST:event_roomTypeComboBoxModelActionPerformed

    private void deleteBtn_roomratesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn_roomratesActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a rate to delete.",
                    "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String roomType = (String) jTable1.getValueAt(selectedRow, 2);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete rates for room type '" + roomType + "'?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/checkinn_db", "root", "@Jonathan123");
                Statement s = con.createStatement();

                ResultSet rs = s.executeQuery("SELECT `id` FROM `room_type` WHERE `type` = '" + roomType + "'");

                if (rs.next()) {
                    int roomTypeId = rs.getInt("id");

                    int rowsDeleted = s.executeUpdate("DELETE FROM `rates` WHERE `room_type_id` = '" + roomTypeId + "'");

                    if (rowsDeleted > 0) {
                        JOptionPane.showMessageDialog(this, "Rates deleted successfully.",
                                "Delete Success", JOptionPane.INFORMATION_MESSAGE);
                        loadRoomRates();
                    } else {
                        JOptionPane.showMessageDialog(this, "No rates found to delete.",
                                "Delete Failed", JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteBtn_roomratesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adultRateField;
    private javax.swing.JTextField childRateField;
    private javax.swing.JButton deleteBtn_roomrates;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> roomTypeComboBoxModel;
    // End of variables declaration//GEN-END:variables
}
