/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lk.checkinn.gui.homescreen.dialog;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import lk.checkinn.gui.homescreen.dialog.info.BookingDetails;
import lk.checkinn.gui.homescreen.dialog.info.CustomerDetails;
import com.formdev.flatlaf.FlatClientProperties;
import java.sql.*;

/**
 *
 * @author DELL
 */
public class NewBookingDialog extends javax.swing.JDialog {

    private BookingDetails bookingDetailsPanel;
    private CustomerDetails customerDetailsPanel;
    private CardLayout contentPanelLayout;

    private NewBookingDialog newBookingDialog;

    public NewBookingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        bookingContentPanel.putClientProperty(FlatClientProperties.STYLE, "arc:20");
        loadPanels();

        updateTotal();
    }

    private void loadPanels() {
        if (contentPanelLayout == null && bookingContentPanel.getLayout() instanceof CardLayout) {
            this.contentPanelLayout = (CardLayout) bookingContentPanel.getLayout();
        }

        bookingDetailsPanel = new BookingDetails();
        customerDetailsPanel = new CustomerDetails();

        bookingContentPanel.add(bookingDetailsPanel, "booking_details");
        bookingContentPanel.add(customerDetailsPanel, "customer_details");
        SwingUtilities.updateComponentTreeUI(bookingContentPanel);

        contentPanelLayout.show(bookingContentPanel, "booking_info");

//        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        backBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        clearBtn = new javax.swing.JButton();
        controlBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bookingContentPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Booking");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Booking");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        clearBtn.setBackground(new java.awt.Color(0, 0, 0));
        clearBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Clear");

        controlBtn.setBackground(new java.awt.Color(0, 102, 255));
        controlBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        controlBtn.setForeground(new java.awt.Color(255, 255, 255));
        controlBtn.setText("Next");
        controlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlBtnActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        backBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quickly register a new room booking by selecting the room and stay.");

        bookingContentPanel.setBackground(new java.awt.Color(84, 84, 84));
        bookingContentPanel.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                                .addComponent(bookingContentPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(controlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void controlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlBtnActionPerformed
        // TODO add your handling code here:
        if (controlBtn.getText().equalsIgnoreCase("next")) {
            contentPanelLayout.next(bookingContentPanel);
            controlBtn.setText("Book");
            clearBtn.setVisible(false);
            backBtn.setVisible(true);
        } else if (controlBtn.getText().equalsIgnoreCase("book")) {
            insertBooking();
            // Optionally close dialog or reset UI here
        }
    }//GEN-LAST:event_controlBtnActionPerformed

    private void insertBooking() {
        try {
            // Get values from booking and customer panels
            java.util.Date checkin = bookingDetailsPanel.getCheckinDate();
            java.util.Date checkout = bookingDetailsPanel.getCheckOutDate();
            int adults = bookingDetailsPanel.getAdultsCount();
            int kids = bookingDetailsPanel.getKidsCount();
            String roomType = bookingDetailsPanel.getSelectedRoomType();
            String roomName = bookingDetailsPanel.getSelectedRoomName();

            String firstName = customerDetailsPanel.getFirstName();
            String lastName = customerDetailsPanel.getLastName();
            String nic = customerDetailsPanel.getNIC();
            String houseNo = customerDetailsPanel.getHouseNo();
            String line1 = customerDetailsPanel.getLine1();
            String line2 = customerDetailsPanel.getLine2();
            String mobile = customerDetailsPanel.getMobile();
            String email = customerDetailsPanel.getEmail();

            // Validation checks
            if (checkin == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select Check-in date.");
                return;
            }
            if (checkout == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select Check-out date.");
                return;
            }
            if (checkout.before(checkin)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Check-out date cannot be before Check-in date.");
                return;
            }
            if (adults <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Number of adults must be at least 1.");
                return;
            }
            if (roomType == null || roomType.equals("Select Room Type")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a Room Type.");
                return;
            }
            if (roomName == null || roomName.equals("Select Room Name")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a Room Name.");
                return;
            }
            if (firstName == null || firstName.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "First name cannot be empty.");
                return;
            }
            if (lastName == null || lastName.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Last name cannot be empty.");
                return;
            }
            if (nic == null || nic.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "NIC cannot be empty.");
                return;
            }
            if (houseNo == null || houseNo.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "House number cannot be empty.");
                return;
            }
            if (line1 == null || line1.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Address Line 1 cannot be empty.");
                return;
            }
            if (mobile == null || !isValidMobile(mobile)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Mobile number must be exactly 10 digits and numeric.");
                return;
            }
            if (email == null || email.trim().isEmpty() || !isValidEmail(email)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
                return;
            }

            // Calculate duration in days (inclusive)
            long diffInMillis = checkout.getTime() - checkin.getTime();
            long durationDays = java.util.concurrent.TimeUnit.DAYS.convert(diffInMillis, java.util.concurrent.TimeUnit.MILLISECONDS) + 1;

            // Database connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/checkinn_db", "root", "@Jonathan123");
            Statement stmt = con.createStatement();

            // Get room_type_id from room_type table
            String getRoomTypeIdQuery = "SELECT id FROM room_type WHERE type = '" + roomType + "'";
            ResultSet rsType = stmt.executeQuery(getRoomTypeIdQuery);
            int roomTypeId = -1;
            if (rsType.next()) {
                roomTypeId = rsType.getInt("id");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Selected room type not found in database.");
                return;
            }
            rsType.close();

            // Get room_name_id from room_name table
            String getRoomNameIdQuery = "SELECT id FROM room_name WHERE name = '" + roomName + "'";
            ResultSet rsName = stmt.executeQuery(getRoomNameIdQuery);
            int roomNameId = -1;
            if (rsName.next()) {
                roomNameId = rsName.getInt("id");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Selected room name not found in database.");
                return;
            }
            rsName.close();

            // Get adult_rate and child_rate from rates table based on room_type_id
            String getRatesQuery = "SELECT adult_rate, child_rate FROM rates WHERE room_type_id = " + roomTypeId;
            ResultSet rsRates = stmt.executeQuery(getRatesQuery);
            double adultRate = 0;
            double childRate = 0;
            if (rsRates.next()) {
                adultRate = rsRates.getDouble("adult_rate");
                childRate = rsRates.getDouble("child_rate");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Rates not found for selected room type.");
                return;
            }
            rsRates.close();

            // Calculate total price
            double totalPrice = (adultRate * adults + childRate * kids) * durationDays;

            // Convert java.util.Date to java.sql.Date for SQL insert
            java.sql.Date sqlCheckin = new java.sql.Date(checkin.getTime());
            java.sql.Date sqlCheckout = new java.sql.Date(checkout.getTime());

            // Insert booking record query with total
            String insertSQL = "INSERT INTO booking (checkin, checkout, adults, kids, room_type_id, room_name_id, first_name, last_name, nic, house_no, line_1, line_2, mobile, email, total) VALUES ("
                    + "'" + sqlCheckin + "', "
                    + "'" + sqlCheckout + "', "
                    + adults + ", "
                    + kids + ", "
                    + roomTypeId + ", "
                    + roomNameId + ", "
                    + "'" + firstName + "', "
                    + "'" + lastName + "', "
                    + "'" + nic + "', "
                    + "'" + houseNo + "', "
                    + "'" + line1 + "', "
                    + "'" + line2 + "', "
                    + "'" + mobile + "', "
                    + "'" + email + "', "
                    + totalPrice
                    + ")";

            int rowsInserted = stmt.executeUpdate(insertSQL);
            
            if (rowsInserted > 0) {
            // Update room status to booked (2)
            String updateRoomSQL = "UPDATE `room_name` SET `booking_status_id` = 1 WHERE id = " + roomNameId;
            stmt.executeUpdate(updateRoomSQL);

            javax.swing.JOptionPane.showMessageDialog(this, "Booking successfully added! Total Price: " + totalPrice);
            jLabel3.setText("Total: " + totalPrice);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to add booking.");
        }

            stmt.close();
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

// Mobile validation method
    private boolean isValidMobile(String mobile) {
        if (mobile == null || mobile.trim().isEmpty()) {
            return false;
        }
        if (mobile.length() != 10) {
            return false;
        }
        for (char c : mobile.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }

// Simple email validation method
    private boolean isValidEmail(String email) {
        if (email == null) {
            return false;
        }
        String emailRegex = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
        return email.matches(emailRegex);
    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        contentPanelLayout.previous(bookingContentPanel);
        clearBtn.setVisible(true);
        backBtn.setVisible(false);
        controlBtn.setText("Next");
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateTotal() {
        try {
            // Get selected room type from BookingDetails
            String roomType = bookingDetailsPanel.getSelectedRoomType();
            if (roomType == null || roomType.equals("Select Room Type")) {
                jLabel3.setText("Total: -");
                return;
            }

            // Get adults and kids count
            int adults = bookingDetailsPanel.getAdultsCount();
            int kids = bookingDetailsPanel.getKidsCount();

            if (adults < 0 || kids < 0) {
                jLabel3.setText("Total: -");
                return;
            }

            // Connect DB and fetch rates for room type
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/checkinn_db", "root", "@Jonathan123");
            Statement stmt = con.createStatement();

            // Get room_type_id for the selected room type
            String getRoomTypeIdQuery = "SELECT id FROM room_type WHERE type = '" + roomType + "'";
            ResultSet rsType = stmt.executeQuery(getRoomTypeIdQuery);
            int roomTypeId = -1;
            if (rsType.next()) {
                roomTypeId = rsType.getInt("id");
            } else {
                jLabel3.setText("Total: -");
                rsType.close();
                stmt.close();
                con.close();
                return;
            }
            rsType.close();

            // Get rates for this room type
            String getRatesQuery = "SELECT adult_rate, child_rate FROM rates WHERE room_type_id = " + roomTypeId;
            ResultSet rsRates = stmt.executeQuery(getRatesQuery);

            double adultRate = 0;
            double childRate = 0;

            if (rsRates.next()) {
                adultRate = rsRates.getDouble("adult_rate");
                childRate = rsRates.getDouble("child_rate");
            } else {
                jLabel3.setText("Total: -");
                rsRates.close();
                stmt.close();
                con.close();
                return;
            }

            rsRates.close();
            stmt.close();
            con.close();

            // Calculate total
            double total = (adults * adultRate) + (kids * childRate);
            jLabel3.setText(String.format("Total: %.2f", total));

        } catch (Exception e) {
            e.printStackTrace();
            jLabel3.setText("Total: Error");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBookingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBookingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBookingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBookingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewBookingDialog dialog = new NewBookingDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bookingContentPanel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton controlBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
